name: TODO Scan After Merge

on:
  push:
    branches:
      - main

# TODO: Switch to true once kratos is re-added to charmcraftcache-hub
jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alstr/todo-to-issue-action@v5
        name: "TODO to Issue"
